# Generated by Django 5.0 on 2023-12-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="recipe",
            name="total_ratings",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
