# Generated by Django 5.0 on 2023-12-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="jwt_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
