# Generated by Django 5.0 on 2023-12-26 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_jwt_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="jwt_token",
        ),
    ]
